extend type Query {
  name: String!
  
  "Get all nested objects"
  nested(id: ID!): Nested
}

type Nested {
  "The id of a nested object"
  id: ID!
  "The name of the nested object"
  name: String!
}
